---

- name: Packages install
  apt: 
    pkg:
      - postgresql
      - python3-pip
    state: present

- name: Pip install
  pip:
    name:
      - psycopg2-binary
    state: present

- name: Verify if postgresql is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

#- name: Postgrade initialize
#  shell: postgresql-setup initdb
#  when: not postgres_data.stat.exist
#  become: true

- name: Start and enable
  service:
    name: postgresql
    state: started
    enabled: true

#- name: restart postgresql
#  service: 
#    name: postgresql
#    state: restarted