---

- name: Update packages installed
  apt:
    name: "*"
    state: latest

- name: Update
  apt:
    upgrade: true
    update_cache: true

- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present

- include_tasks: database_install.yml

- include_tasks: database_create.yml
