---

- name: Setup
  hosts: staging, production
  remote_user: weles
  become: true
  roles:
    - setup

- name: Database
  hosts: master
  remote_user: weles
  become: true
  roles:
    - database_setup
